name: Android Release (TWA)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          sdkmanager --licenses <<< "y"
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      # Restore keystore from GitHub Secrets
      - name: Restore keystore
        run: echo "$KEYSTORE_BASE64" | base64 -d > $GITHUB_WORKSPACE/keystore.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Create signing gradle.properties
        run: |
          cat >> "$GITHUB_WORKSPACE/gradle.properties" <<'EOF'
          MY_KEYSTORE_PATH=keystore.jks
          MY_KEY_ALIAS=${{ secrets.KEY_ALIAS }}
          MY_KEY_STORE_PASSWORD=${{ secrets.KEY_STORE_PASSWORD }}
          MY_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}
          EOF

      - name: Build AAB
        run: ./gradlew bundleRelease --stacktrace

      - name: Build APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-artifacts
          path: |
            app/build/outputs/bundle/release/*.aab
            app/build/outputs/apk/release/*.apk
